# Generated by Django 6.0 on 2026-01-31 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolemodulepermission',
            name='can_add',
        ),
        migrations.RemoveField(
            model_name='rolemodulepermission',
            name='can_delete',
        ),
        migrations.RemoveField(
            model_name='rolemodulepermission',
            name='can_edit',
        ),
        migrations.RemoveField(
            model_name='rolemodulepermission',
            name='can_view',
        ),
        migrations.CreateModel(
            name='ModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('crud', 'CRUD'), ('column', 'Column'), ('component', 'Component'), ('action', 'Action'), ('field', 'Field')], default='crud', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_permissions', to='modules.module')),
            ],
            options={
                'verbose_name': 'Module Permission',
                'verbose_name_plural': 'Module Permissions',
                'db_table': 'module_permissions',
                'ordering': ['category', 'order', 'codename'],
                'unique_together': {('module', 'codename')},
            },
        ),
        migrations.AddField(
            model_name='rolemodulepermission',
            name='granted_permissions',
            field=models.ManyToManyField(blank=True, related_name='role_grants', to='modules.modulepermission'),
        ),
    ]
